### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by clementbirkle** [hanFengSan/nestjs-agenda#1]
Hi,

Your module is nice but is it possible to update dependencies like:
* agenda: ^3.1.0

Thank you very much ! :)

**Comment by hanFengSan** [comment]
thx，I will update it today.

Clément Birklé <notifications@github.com> 于 2020年4月17日周五 00:32写道：

**Comment by hanFengSan** [comment]
I updated it to version 2.0.0. You can try it.

**Comment by clementbirkle** [comment]
Thank you very much hanFengSan, it works well ! 

I have just a warning with MongoDB:
`(node:65749) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.`

But I think it comme from agenda and his dependencies.

**Comment by hanFengSan** [comment]
https://github.com/agenda/agenda/pull/921

So, if you have a Mongo client:
```TypeScript
import { AgendaModule } from 'nestjs-agenda';

@Module({
  imports: [AgendaModule.register({ mongo: client.db() })], // Same as configuring an agenda  
  providers: [...],
})
export class FooModule {}
```

It seems very simple, but how to get a Mongo client by NestJS is not easy.

**Comment by clementbirkle** [comment]
Thank you for this solution! I will investigate this when I have time. Actually it works well without this Mongo Client.
